export enum CellActionTypes {
  INSERT_CELL = "INSERT_CELL",
  MOVE_CELL = "MOVE_CELL",
  DELETE_CELL = "DELETE_CELL",
  UPDATE_CELL = "UPDATE_CELL",
  FETCH_CELLS = "FETCH_CELLS",
  FETCH_CELLS_COMPLETE = "FETCH_CELLS_COMPLETE",
  FETCH_CELLS_ERROR = "FETCH_CELLS_ERROR",
  SAVE_CELLS_ERROR = "SAVE_CELLS_ERROR",
}
